language: c

# https://docs.travis-ci.com/user/languages/c/#gcc-on-macos
# On mac, gcc is aliased to clang, so we only have one row 
# in build the matrix, not two like on linux
compiler:
  - clang
  - gcc

jobs:
  include:
    - os: linux
    - os: osx
      env: WREN_TARGET_MAC=1

# Travis VMs are 64-bit but we compile both for 32 and 64 bit. To enable the
# 32-bit builds to work, we need gcc-multilib.
addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib

dist: trusty

script: ./.travis.sh
